### ISSUE TITLE
Danger Quest Knights: Version #1

### ISSUE THREAD

**Issue by ashes999** [ashes999/rpg-maker-experiments#3]
First version must have at a minimum:
- [x] Pick the main character (or throw them all  out)
- [x] Khalifa gives you a quest: get the crystal from the dragon in the forest.
  - [x] Fix bug: khalifa text is cut off
- [x] Fix bug: blue border around game
- [x] World map: find the forest
- [x] Full quest (including completion)
  - [x] Ask what quest he wants. (Dragon Quest)
  - [x] Forest map
  - [x] Big dragon character
  - [x] Dragon face
  - [x] Dragon chases you
  - [x] You die or get hurt if the dragon catches you
  - [x] Crystal sprite
  - [x] You can take the crystal
  - [x] You can see it in your inventory (+picture?)
  - [x] The khalifa tells you how awesome you are when you win (+reward?)
# TODO: second version
- Gold and equipment
- Gold on quest completion
- Town
- Buy stuff in shops around town
